### PR TITLE
fix throttle scale from 0,100 to [-63,63]

### PR DESCRIPTION
**Pull request by yaapu**
same as ardupilot (throttle from vfr hud is still unchanged and positive only)

### CODE REVIEW

**Review by zs6buj — APPROVED** [review]

**Comment by zs6buj** [comment]
Thanks Alex. I'll make this V2.65.1

**Comment by yaapu** [comment]
ok thanks Eric, we need to do a debug session because I see some strange behaviour with the new frames, the log reports sending the correct values but my dump on OpenTX shows different, let meknow when you'll have some time

**Comment by zs6buj** [comment]
Alex I have some tools that I use, like a second esp32 that reads and decodes. They can read either serial, or udp. I can post them for you. In the meantime I have retrieved a box from storage with the more important bits that I need, but I need to figure out where and how to set up with a GPS signal.

**Comment by zs6buj** [comment]
I just posted this:  https://github.com/zs6buj/FrSky_Tools

I also use my antenna tracker code to read passthru UDP and decode. Libs are in 
https://github.com/zs6buj/AntTracker/tree/master/libraries

**Comment by yaapu** [comment]
> but I need to figure out where and how to set up with a GPS signal.

I use ardupilot SITL simulator with an FTDI adapter and pump mavlink from the simulator to the MavToPT port, if you have a running Lnux box it's quite easy

**Comment by zs6buj** [comment]
I have a laptop with Ubuntu on it, or my dev box also runs WSL, but never really got into SITL. Maybe it's time.

**Comment by yaapu** [comment]
It's just so simple to do proper testing, I mean you can check all features on the bench, like rpm, fencing, missions, multiple bvatteries, really cool. My daily dev work is on an ubuntu VM, serial ports work nicely whereas in WSL I often have troubles

**Comment by zs6buj** [comment]
Alex, would it be possible to give me  TLog where the manual flight mode is ignored? This might save a lot of time. I've been combing through storage boxes in a cramped facility to find my Ubuntu laptop. It's difficult work without success so far. :(

**Comment by yaapu** [comment]
Sure Eric,
the test I'm doing is toggling the bit at offset 13 of 0x5001 on/off, this bit is FENCE_ENABLE=1/0, I did some tracing as well so I disabled all frames but 0x5001 and 0xF101.
This is your debug
```
FENCE_ENABLE = 0
 FrPeriod mS=306	Passthru out AP_status 0x5001:  pt_flight_mode=1 pt_simple=0 pt_land_complete=0 pt_armed=0 pt_bat_fs=0 pt_ekf_fs=0 pt_fs=0 pt_fence_present=0 pt_fence_breached=0 pt_imu_temp=0 pt_throt=0 pt_payload=1  passthru payload 0x10 01>00>00>00>	....	
 FrPeriod mS=1017	Passthru out AP_status 0x5001:  pt_flight_mode=1 pt_simple=0 pt_land_complete=0 pt_armed=0 pt_bat_fs=0 pt_ekf_fs=0 pt_fs=0 pt_fence_present=0 pt_fence_breached=0 pt_imu_temp=0 pt_throt=0 pt_payload=1  passthru payload 0x10 01>00>00>00>	....	
 FrPeriod mS=987	Passthru out AP_status 0x5001:  pt_flight_mode=1 pt_simple=0 pt_land_complete=0 pt_armed=0 pt_bat_fs=0 pt_ekf_fs=0 pt_fs=0 pt_fence_present=0 pt_fence_breached=0 pt_imu_temp=0 pt_throt=0 pt_payload=1  passthru payload 0x10 01>00>00>00>	....	
 FrPeriod mS=1013	Passthru out AP_status 0x5001:  pt_flight_mode=1 pt_simple=0 pt_land_complete=0 pt_armed=0 pt_bat_fs=0 pt_ekf_fs=0 pt_fs=0 pt_fence_present=0 pt_fence_breached=0 pt_imu_temp=0 pt_throt=0 pt_payload=1  passthru payload 0x10 01>00>00>00>	....	
 FrPeriod mS=986	Passthru out AP_status 0x5001:  pt_flight_mode=1 pt_simple=0 pt_land_complete=0 pt_armed=0 pt_bat_fs=0 pt_ekf_fs=0 pt_fs=0 pt_fence_present=0 pt_fence_breached=0 pt_imu_temp=0 pt_throt=0 pt_payload=1  passthru payload 0x10 01>00>00>00>	....	
 FrPeriod mS=1001	Passthru out AP_status 0x5001:  pt_flight_mode=1 pt_simple=0 pt_land_complete=0 pt_armed=0 pt_bat_fs=0 pt_ekf_fs=0 pt_fs=0 pt_fence_present=0 pt_fence_breached=0 pt_imu_temp=0 pt_throt=0 pt_payload=1  passthru payload 0x10 01>00>00>00>	....	

FENCE_ENABLE = 1
 FrPeriod mS=997	Passthru out AP_status 0x5001:  pt_flight_mode=1 pt_simple=0 pt_land_complete=0 pt_armed=0 pt_bat_fs=0 pt_ekf_fs=0 pt_fs=0 pt_fence_present=1 pt_fence_breached=0 pt_imu_temp=0 pt_throt=0 pt_payload=8193  passthru payload 0x10 01>20>00>00>	. ..	
 FrPeriod mS=998	Passthru out AP_status 0x5001:  pt_flight_mode=1 pt_simple=0 pt_land_complete=0 pt_armed=0 pt_bat_fs=0 pt_ekf_fs=0 pt_fs=0 pt_fence_present=1 pt_fence_breached=0 pt_imu_temp=0 pt_throt=0 pt_payload=8193  passthru payload 0x10 01>20>00>00>	. ..	
 FrPeriod mS=1071	Passthru out AP_status 0x5001:  pt_flight_mode=1 pt_simple=0 pt_land_complete=0 pt_armed=0 pt_bat_fs=0 pt_ekf_fs=0 pt_fs=0 pt_fence_present=1 pt_fence_breached=0 pt_imu_temp=0 pt_throt=0 pt_payload=8193  passthru payload 0x10 01>20>00>00>	. ..	
 FrPeriod mS=974	Passthru out AP_status 0x5001:  pt_flight_mode=1 pt_simple=0 pt_land_complete=0 pt_armed=0 pt_bat_fs=0 pt_ekf_fs=0 pt_fs=0 pt_fence_present=1 pt_fence_breached=0 pt_imu_temp=0 pt_throt=0 pt_payload=8193  passthru payload 0x10 01>20>00>00>	. ..	
 FrPeriod mS=999	Passthru out AP_status 0x5001:  pt_flight_mode=1 pt_simple=0 pt_land_complete=0 pt_armed=0 pt_bat_fs=0 pt_ekf_fs=0 pt_fs=0 pt_fence_present=1 pt_fence_breached=0 pt_imu_temp=0 pt_throt=0 pt_payload=8193  passthru payload 0x10 01>20>00>00>	. ..	

```
here the tlogs
[mav_fence_enable_tlog.zip](https://github.com/zs6buj/MavlinkToPassthru/files/6489067/mav_fence_enable_tlog.zip)

this is a an 0x5001 packet that was sent but not accepted by OpenTX (I suspect a CRC issue here)
image
and finally this the tracing of the FENCE_ENABLE=1 session (you need saleae logic to view it)
[ap_status_bad_packet.zip](https://github.com/zs6buj/MavlinkToPassthru/files/6489070/ap_status_bad_packet.zip)

**Comment by zs6buj** [comment]
Great, thanks Alex. Lots to look at. I just got my dev machine up and running, and will try to tackle this tomorrow.

**Comment by zs6buj** [comment]
Thank you for all the debug data, and the tool. 

I had a quick look and think you are right about the CRC. From your debug data, it looks like the last byte on the wire is CRC == 0x7D, which is a special bytestuff case, and must be suspicious.

Could you try change line 1437 in FrSky_Ports.h from

  `    FrSkyPort::SafeWrite(byte, false);`
to 
  `    FrSkyPort::WriteByte(byte);`

I can try #define Debug_CRC tomorrow, or if you feel inclined you could try it to see how the crc is built up.

**Comment by yaapu** [comment]
yep it was the CRC but stuffing the CRC is required as per specs so the fix was 

`FrSkyPort::SafeWrite(byte, false);`

Working fine now :-)

**Comment by yaapu** [comment]
...but I'm getting status text corruption

**Comment by yaapu** [comment]
OK enabling debug for Status text fixed the issue, so I guess packets come into the radio just too fast, need a little delay between them, this just for 0x5000

**Comment by yaapu** [comment]
...and only for Horus radios, I can't push the background loop too hard, right now I'm at 90Hz, keep in mind that on actual frsky hardware the packet rate never exceeds 60Hz (used to be 40Hz but now ardupilot uses 3 sensors for downlink)

**Comment by zs6buj** [comment]
Ah man, you nailed it! Bravo Alex. What delay works for the Horus.  A few mS between chunks?

**Comment by yaapu** [comment]
Yeah a few ms, I'd stay below 80hz so like 12-15. One left issue is corruption of frames 0x500a and 0x500b every once in a while even though I do not see anything obvious

**Comment by zs6buj** [comment]
0x500a and 0x500b

After fixing the crc/stuffbyte issue?

**Comment by yaapu** [comment]
Yes, I see values jumping from expected range to very big or negative values, log on your side shows correct values, so not sure what's going on, I need to trace those packets as well

**Comment by yaapu** [comment]
ok so RPM is fixed but there's something in the bit32pack function??

this does not work

```
      bit32Pack(pt_rpm1, 0, 16);
      bit32Pack(pt_rpm2, 16, 16);

```      
this works

`      pt_payload = pt_rpm1 | (pt_rpm2 << 16);`

**Comment by yaapu** [comment]
```
// Mask then AND the shifted bits, then OR them to the payload
  void bit32Pack(uint32_t dword ,uint8_t displ, uint8_t lth) {   
  uint32_t dw_and_mask =  (dword<<displ) & (createMask(displ, displ+lth-1)); 
  pt_payload |= dw_and_mask; 
}
```
this method assumes an uint32_t as first argument, but for 0x500A and 0x500B I pass an int16_t and uint8_t triggering an implicit cast that seems to fail under some circumstances... no clues, perhaps a compiler optimization kicking in?

**Comment by yaapu** [comment]
same for 0x500B (terrain), this works

```
      //bit32Pack(pt_height_above_terrain, 0, 13);
      //bit32Pack(pt_terrain_unhealthy, 13, 1);

      pt_payload = pt_height_above_terrain | (pt_terrain_unhealthy << 13);
```

**Comment by zs6buj** [comment]
Lol. Ok, I solved this after staring at it for a while.

First line in each push function should initialise the payload = 0 before building the bit field

`      pt_payload = 0;`

Like this:

    void FrSkyPort::Push_RPM_500A(uint16_t msg_id) {
      pt_payload = 0;
      pt_rpm1 = (int16_t)roundf(  * 0.1);
      pt_rpm2 = (int16_t)roundf(ap_rpm2 * 0.1);

      bit32Pack(pt_rpm1, 0, 16);
      bit32Pack(pt_rpm2, 16, 16);
      
     // pt_payload = pt_rpm1 | (pt_rpm2 << 16);

**Comment by yaapu** [comment]
ahhhh...thanks Eric, my fault..should have done a better copy&paste job :-)

**Comment by zs6buj** [comment]
You could have a situation where you are pushing onto the table, but pops and sends are held up, for example, by no S.Port link. In this case the table fills up and notifies an S.Port problem, but the point is that push and pop are not synchronised.

I did consider zeriosing the payload on start of PopNextFrame(), through which all sends flow, but I need to check the implications, like for 0x5000 chunking.

**Comment by yaapu** [comment]
ok Eric it's your code and you sure deserve the right to decide what is good and what is bad :-)

**Pull request merged**
