### PR TITLE
added support for MAVLINK RANGEFINDER message #173

### PR DESCRIPTION
**Pull request by yaapu**
Hi Eric,
ardupilot frsky passthru library already supports rangefinder, all was missing in your code was the mavlink message decoding.

### CODE REVIEW

**Comment by jregholdsworth** [comment]
This looks like what I was looking for....Presumably youre going to add bluetooth or wifi to the esp32 branch of this programme?
If not I'll have a go at doing it.
Ps been to Midrand many times ..particularly to the Gallagher estate

**Comment by zs6buj** [comment]
Hey jregholdsworth 

Yes, I'm into the BLE learning curve, and hopefully something will pop out some time. 

Yes, I'm not all that far from Gallagher. I assume you attend conferences there?

**Comment by jregholdsworth** [comment]
Well back in the mid 90s, (after Madela was released) we had offices near the Eskom building on William Nicol..My Canadian employer built a telecoms/data network to suport the election which I was heavily involved in, (with the permission of the UN and Canadian governement)) I did a few conferences at the Gallagher and in those days there was an african meat restuarant there too.. also visited the Boulders shopping centre a bit..stayed at the Protea in midrand a few times too, but spent most of my time in Cape town since our target customer was there.

**Comment by yaapu** [comment]
thanks for merging

**Comment by zs6buj** [comment]
Oops, my bad Alex, sorry. I have been using the git desktop and missed the pull request way back when you first sent it, then yesterday screwed it up trying to arrange git  structure better.

**Comment by yaapu** [comment]
ok, no big deal, if nobody asked than it's not used I guess.
I sent you a PR back then when I was testing rangefinder rendering on my script

**Pull request merged**
